### ISSUE TITLE
Power supply

### ISSUE THREAD

**Issue by jbree** [siddolo/happyswitch#1]
Were you able to power your microcontroller directly from amp supply? I can't find any indication from mesa about how much current the footswitch port can provide.

Also, thanks for the technical info on your (now defunct) blog. I found it using the wayback machine, and it helped confirm some of the reverse engineering I did, and filled in some gaps in my knowledge.

Do you have any plans to put the happyswitch site and your blog back up? I wasnt able to view your images, which would surely be helpful.

**Comment by siddolo** [comment]
Hi,
yes, i'm able to pwer up arduino directly from the amp (Pin 2 +5V and Pin 1 GND).
Sorry for the technical issue with my blog, happyswitch.it and blog.pasqualefiorillo.it are both up and running now.

**Comment by jbree** [comment]
I really appreciate you putting it back up! Thanks for the info.

My footswitch is slightly different than yours, as it also includes a mute switch. It appears that on mine, pin 4 controls the "mute" setting (low = mute), and pin 7 controls the solo same as yours. For reference, mine is a BigFoot 3.

Lastly, i noticed that in your diagrams of the DIN connector, your numberings appear to have male and female reversed from what I have on my connectors.

Thanks again!
